widgetshop:
  baseUrl: http://localhost:8080
  oauth2:
    client:
      grantType: client_credentials
      clientId: 0oahz1q4Qosx0io5z5d5
      clientSecret: BCVSn5hKiv2JbkjYGFkcEAcqMfw5_66aWEXxeSQi
      accessTokenUri: https://dev-1951019.okta.com/oauth2/default/v1/token
      scope: custom_mod